### PR TITLE
Feature: HTTP Job runners / Socket message handling / User Settings Pane

### PR DESCRIPTION
**Pull request by josh-keating**
This also includes ejecting of the create-react-native-app.

### CODE REVIEW

**Comment by josh-keating** [comment]
As I've closed / deleted the previous PR, this also includes creation of renderless components:
JobRunner
Device
Socket Client

Retrieval and storing of device specific data:
lat / long
device_type
minder_id (from storage or socket message)

**Comment by josh-keating** [comment]
Also added user settings pane to this PR.

**Comment by jvke** [comment]
Anything we need from here into upstream or can I close and delete this @josh-keating

**Comment by josh-keating** [comment]
Close and delet this @jvke  😎

**Pull request closed without merging**
